leftSideOfMonitoringArea = monitoringArea.getSegments{4};
idxSensorsLeftSideMonitoringAreaIntersections = findMonitoringAreaSideIntersections(...
    leftSideOfMonitoringArea, ordSensors ...
    );
idxSensorsLeftSideMonitoringAreaIntersections